"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class IncidentsAcknowledgeIncidentRequestTypedDict(TypedDict):
    incident_id: str


class IncidentsAcknowledgeIncidentRequest(BaseModel):
    incident_id: Annotated[
        str,
        pydantic.Field(alias="incidentID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class IncidentsAcknowledgeIncidentResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: str


class IncidentsAcknowledgeIncidentResponse(BaseModel):
    r"""The request has succeeded."""

    data: str
