"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_incidents_incidentresponse import (
    V3IncidentsIncidentResponse,
    V3IncidentsIncidentResponseTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class IncidentsGetIncidentByIDRequestTypedDict(TypedDict):
    incident_id: str


class IncidentsGetIncidentByIDRequest(BaseModel):
    incident_id: Annotated[
        str,
        pydantic.Field(alias="incidentID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class IncidentsGetIncidentByIDResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: V3IncidentsIncidentResponseTypedDict


class IncidentsGetIncidentByIDResponse(BaseModel):
    r"""The request has succeeded."""

    data: V3IncidentsIncidentResponse
