"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class IncidentActionsCreateAnIncidentInServicenowRequestTypedDict(TypedDict):
    incident_id: str


class IncidentActionsCreateAnIncidentInServicenowRequest(BaseModel):
    incident_id: Annotated[
        str,
        pydantic.Field(alias="incidentID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class IncidentActionsCreateAnIncidentInServicenowResponseTypedDict(TypedDict):
    r"""The request has succeeded and a new resource has been created as a result."""


class IncidentActionsCreateAnIncidentInServicenowResponse(BaseModel):
    r"""The request has succeeded and a new resource has been created as a result."""
