"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v4_statuspages_maintenances_deletemaintenancebyidresponse import (
    V4StatusPagesMaintenancesDeleteMaintenanceByIDResponse,
    V4StatusPagesMaintenancesDeleteMaintenanceByIDResponseTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class MaintenancesDeleteMaintenanceByIDRequestTypedDict(TypedDict):
    statuspage_id: str
    maintenance_id: str


class MaintenancesDeleteMaintenanceByIDRequest(BaseModel):
    statuspage_id: Annotated[
        str,
        pydantic.Field(alias="statuspageID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    maintenance_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class MaintenancesDeleteMaintenanceByIDResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: V4StatusPagesMaintenancesDeleteMaintenanceByIDResponseTypedDict


class MaintenancesDeleteMaintenanceByIDResponse(BaseModel):
    r"""The request has succeeded."""

    data: V4StatusPagesMaintenancesDeleteMaintenanceByIDResponse
