"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_services_overlay_customcontentoverlayresponse import (
    V3ServicesOverlayCustomContentOverlayResponse,
    V3ServicesOverlayCustomContentOverlayResponseTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class OverlayGetAllCustomContentTemplateOverlayByServiceRequestTypedDict(TypedDict):
    service_id: str


class OverlayGetAllCustomContentTemplateOverlayByServiceRequest(BaseModel):
    service_id: Annotated[
        str,
        pydantic.Field(alias="serviceID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class OverlayGetAllCustomContentTemplateOverlayByServiceResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: List[V3ServicesOverlayCustomContentOverlayResponseTypedDict]


class OverlayGetAllCustomContentTemplateOverlayByServiceResponse(BaseModel):
    r"""The request has succeeded."""

    data: List[V3ServicesOverlayCustomContentOverlayResponse]
