"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class OverlayGetOptinForKeyBasedDeduplicationForAServiceRequestTypedDict(TypedDict):
    service_id: str


class OverlayGetOptinForKeyBasedDeduplicationForAServiceRequest(BaseModel):
    service_id: Annotated[
        str,
        pydantic.Field(alias="serviceID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class OverlayGetOptinForKeyBasedDeduplicationForAServiceDataTypedDict(TypedDict):
    dedup_key_enabled: bool


class OverlayGetOptinForKeyBasedDeduplicationForAServiceData(BaseModel):
    dedup_key_enabled: bool


class OverlayGetOptinForKeyBasedDeduplicationForAServiceResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: OverlayGetOptinForKeyBasedDeduplicationForAServiceDataTypedDict


class OverlayGetOptinForKeyBasedDeduplicationForAServiceResponse(BaseModel):
    r"""The request has succeeded."""

    data: OverlayGetOptinForKeyBasedDeduplicationForAServiceData
