"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .common_v4_pageinfo import CommonV4PageInfo, CommonV4PageInfoTypedDict
from .v4_rotationresponse import V4RotationResponse, V4RotationResponseTypedDict
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class RotationsGetScheduleRotationsRequestTypedDict(TypedDict):
    schedule_id: str


class RotationsGetScheduleRotationsRequest(BaseModel):
    schedule_id: Annotated[
        str,
        pydantic.Field(alias="scheduleID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class RotationsGetScheduleRotationsResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: List[V4RotationResponseTypedDict]
    page_info: CommonV4PageInfoTypedDict


class RotationsGetScheduleRotationsResponse(BaseModel):
    r"""The request has succeeded."""

    data: List[V4RotationResponse]

    page_info: Annotated[CommonV4PageInfo, pydantic.Field(alias="pageInfo")]
