"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_runbooks_runbookresponse import (
    V3RunbooksRunbookResponse,
    V3RunbooksRunbookResponseTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class RunbooksGetRunbookByIDRequestTypedDict(TypedDict):
    runbook_id: str


class RunbooksGetRunbookByIDRequest(BaseModel):
    runbook_id: Annotated[
        str,
        pydantic.Field(alias="runbookID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class RunbooksGetRunbookByIDResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: V3RunbooksRunbookResponseTypedDict


class RunbooksGetRunbookByIDResponse(BaseModel):
    r"""The request has succeeded."""

    data: V3RunbooksRunbookResponse
