"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class StatusPagesListStatusPagesRequestTypedDict(TypedDict):
    page_size: str
    page_number: str
    filters_is_public: str
    team_id: str


class StatusPagesListStatusPagesRequest(BaseModel):
    page_size: Annotated[
        str,
        pydantic.Field(alias="pageSize"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ]

    page_number: Annotated[
        str,
        pydantic.Field(alias="pageNumber"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ]

    filters_is_public: Annotated[
        str,
        pydantic.Field(alias="filters.isPublic"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ]

    team_id: Annotated[
        str,
        pydantic.Field(alias="teamID"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ]
