"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v4_statuspages_deletestatuspagebyidresponse import (
    V4StatusPagesDeleteStatusPageByIDResponse,
    V4StatusPagesDeleteStatusPageByIDResponseTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class StatusPagesDeleteStatusPageByIDRequestTypedDict(TypedDict):
    statuspage_id: str


class StatusPagesDeleteStatusPageByIDRequest(BaseModel):
    statuspage_id: Annotated[
        str,
        pydantic.Field(alias="statuspageID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class StatusPagesDeleteStatusPageByIDResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: V4StatusPagesDeleteStatusPageByIDResponseTypedDict


class StatusPagesDeleteStatusPageByIDResponse(BaseModel):
    r"""The request has succeeded."""

    data: V4StatusPagesDeleteStatusPageByIDResponse
