"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class UsersRemoveUserFromOrgRequestTypedDict(TypedDict):
    user_id: str
    r"""(Required) user id"""


class UsersRemoveUserFromOrgRequest(BaseModel):
    user_id: Annotated[
        str,
        pydantic.Field(alias="userID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""(Required) user id"""


class UsersRemoveUserFromOrgResponseBodyTypedDict(TypedDict):
    r"""There is no content to send for this request, but the headers may be useful."""


class UsersRemoveUserFromOrgResponseBody(BaseModel):
    r"""There is no content to send for this request, but the headers may be useful."""
