"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class UsersRemoveTokenRequestTypedDict(TypedDict):
    refresh_token_id: str
    r"""(Required) refresh token id"""


class UsersRemoveTokenRequest(BaseModel):
    refresh_token_id: Annotated[
        str,
        pydantic.Field(alias="refreshTokenID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""(Required) refresh token id"""


class UsersRemoveTokenResponseBodyTypedDict(TypedDict):
    r"""There is no content to send for this request, but the headers may be useful."""


class UsersRemoveTokenResponseBody(BaseModel):
    r"""There is no content to send for this request, but the headers may be useful."""
