"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class V4StatusPagesIssuesUpdateIssueResponseTypedDict(TypedDict):
    id: int
    component_i_ds: List[int]
    title: str


class V4StatusPagesIssuesUpdateIssueResponse(BaseModel):
    id: int

    component_i_ds: Annotated[List[int], pydantic.Field(alias="componentIDs")]

    title: str
