"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class V4StatusPagesTotalSubscribersCountTypedDict(TypedDict):
    total_count: int


class V4StatusPagesTotalSubscribersCount(BaseModel):
    total_count: Annotated[int, pydantic.Field(alias="totalCount")]
