"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_webforms_webformresponse import (
    V3WebformsWebformResponse,
    V3WebformsWebformResponseTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WebformsGetWebformByIDRequestTypedDict(TypedDict):
    webform_id: int
    owner_id: NotRequired[str]


class WebformsGetWebformByIDRequest(BaseModel):
    webform_id: Annotated[
        int,
        pydantic.Field(alias="webformId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    owner_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None


class WebformsGetWebformByIDResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: V3WebformsWebformResponseTypedDict


class WebformsGetWebformByIDResponse(BaseModel):
    r"""The request has succeeded."""

    data: V3WebformsWebformResponse
