"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WebhooksGetAllWebhooksRequestTypedDict(TypedDict):
    page_limit: NotRequired[str]
    offset: NotRequired[str]


class WebhooksGetAllWebhooksRequest(BaseModel):
    page_limit: Annotated[
        Optional[str],
        pydantic.Field(alias="page-limit"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    offset: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
