"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class WorkflowsDeleteWorkflowRequestTypedDict(TypedDict):
    workflow_id: str


class WorkflowsDeleteWorkflowRequest(BaseModel):
    workflow_id: Annotated[
        str,
        pydantic.Field(alias="workflowID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class WorkflowsDeleteWorkflowResponseBodyTypedDict(TypedDict):
    r"""There is no content to send for this request, but the headers may be useful."""


class WorkflowsDeleteWorkflowResponseBody(BaseModel):
    r"""There is no content to send for this request, but the headers may be useful."""
